### ISSUE TITLE
DiscordPHP Interaction requirements

### ISSUE THREAD

**Issue by Corin123555** [discord-php/DiscordPHP-Slash#13]
Hey, I went to experiment with DiscordPHP on the dev-develop branch to try out the new MessageBuilder class for buttons and found the requirements have changed for discord/interactions to v2.

As a result, it conflicts with DiscordPHP-Slash's interactions v1 requirement so the two can't be used together.
Is this intended to be fixed by the release of the dev-develop branch?

Thanks!

**Comment by davidcole1340** [comment]
Will take a look today. Just FYI with the way Discord bots are moving this library will probably be deprecated in favour of integrating slash commands into DiscordPHP.

**Comment by Corin123555** [comment]
Sounds good, more streamlined that way at least.
Thanks for that! :)

**Comment by SQKo** [comment]
[DiscordPHP v7.0.0](https://github.com/discord-php/DiscordPHP/releases/tag/v7.0.0) now implements its own slash command integration.
