### ISSUE TITLE
Use embed objects in follow up messages

### ISSUE THREAD

**Issue by 0x346e3730** [discord-php/DiscordPHP-Slash#8]
![image](https://user-images.githubusercontent.com/28731165/113511766-def69380-9561-11eb-8cb8-75aaa228fe55.png)

Currently, you need to pass the embeds as objects, because encoding the json serialized version adds every value that is also null, making the request a bad one (adding `->setType('rich')` still produces a 400).

It would be best to be able to use PHP Embeds object instead.

**Comment by valzargaming** [comment]
Update to latest dev-master, change to [embed], then try running it again. Newest commit should have resolved this, tested and confirmed working.
